export const data = [
  {
    question: "What is the capital city of Bangladesh?",
    option1: "Dhaka",
    option2: "Birgonj",
    option3: "Chittagong",
    option4: "Dinajpur",
    ans: 1,
  },
  {
    question: "What is the largest ocean in the world?",
    option1: "Atlantic Ocean",
    option2: "Indian Ocean",
    option3: "Arctic Ocean",
    option4: "Pacific Ocean",
    ans: 4,
  },
  {
    question: "Who wrote 'Hamlet'?",
    option1: "Leo Tolstoy",
    option2: "William Shakespeare",
    option3: "Mark Twain",
    option4: "Jane Austen",
    ans: 2,
  },
  {
    question: "Which planet is known as the Red Planet?",
    option1: "Venus",
    option2: "Jupiter",
    option3: "Mars",
    option4: "Saturn",
    ans: 3,
  },
  {
    question: "What is the smallest prime number?",
    option1: "0",
    option2: "1",
    option3: "2",
    option4: "3",
    ans: 3,
  },
  {
    question: "What is the boiling point of water?",
    option1: "90°C",
    option2: "80°C",
    option3: "100°C",
    option4: "120°C",
    ans: 3,
  },
  {
    question: "Who is the author of '1984'?",
    option1: "George Orwell",
    option2: "Aldous Huxley",
    option3: "J.K. Rowling",
    option4: "F. Scott Fitzgerald",
    ans: 1,
  },
];
